include(${CMAKE_CURRENT_LIST_DIR}/dep_versions.cmake)

if(ENABLE_OFFLINE_BUILD)
ExternalProject_Add(EcpInt_External
    URL ${DEPS_LOCAL_PATH}/libecpint
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DLIBECPINT_BUILD_TESTS=OFF -DLIBECPINT_USE_PUGIXML=OFF
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)
else()
ExternalProject_Add(EcpInt_External
    GIT_REPOSITORY https://github.com/dmejiar/libecpint.git
    GIT_TAG master
    UPDATE_DISCONNECTED 1
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} -DLIBECPINT_BUILD_TESTS=OFF -DLIBECPINT_USE_PUGIXML=OFF
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)
endif()
